//BASE STRUCTURE OF OBJECT
// const def = {
//     header: "",
//     subheader: "",
//     subheader1: "",
//     subheader2: "",
//     subheader3: "",
//     checkedtextchat: [{head:"",body:""}],
//     search: [{title:"",children: [""]}],
//     checkedtext: []
// }

export const AdminFeatures = {
    header: "Features",
    subheader: "NEWS TAB",
    checkedtext: ["It features news managed by the admin of the organization detailing a curated selection of the day’s top stories, urgent information is instantaneous and broadly displayed.","It allows employees be part of a larger conversation with all information on one platform. There is control of news dissemination thereby curbing false alarms, and misinformation while also reining extreme views.","Employees can read news anytime whenever they wish and able to read information again and again.","Past news can be searched by date.","Users can also like, dislike and comment on various news stories posted by the admin."]
}

export const AdminEvents = {
    header: "EVENT AND TRAINING MANAGEMENT TAB",
    checkedtext: ["This tab showcases all events as it relates to all organization and its employees.","An event can be scheduled as recurring or a one-off e.g., meetings.","There is categorization of events based on attendees of the event or the peculiarity of the event.","Some events can be strictly for executives, employees, group employees, class employees, etc.","The categorization is created by the admin to avoid misinformation.","Events can be virtual, hybrid or physical as it allows for employees to register and login to the online meeting via its interface with zoom, google team etc.","Employees can search for past events by date and type.","Registration for training programmes within the organization is captured through the event and training management mobile.","Participants can login via the Rel8 app is training virtual.","Records of participants can be generated by the admin whenever such is required."]
}

export const AdminChat = {
    header: "CHAT MANAGEMENT",
    subheader: "The chat feature creates an avenue for faster communication and decision making without necessarily waiting to see in person. It creates an avenue for bonding while promoting trust.",
    subheader1: "Communication can in turn fuel productivity among while creating clarity among community employees. The chat section is divided into 4 main categories:",
    checkedtextchat: [{head:"Global chat for employees",body:"a. This applies to organizations with global or national spread."},{head:"Branch Office Based Chats",body:"a. This applies to organizations with branches."},{head:"Committee chat",body:"a. Different committees will have their committee chat group created with employees of such committee as the only active participants. –"},{head:"Executive team members chat",body:"a. Employees of the executive forum are the only ones allowed in this sub categories of chat groups."},{head:"Management team members chat",body:"a. Employees of the management forum are the only ones allowed in this sub categories of chat groups."},{head:"One-on-One chat",body:"a. Employees can also interact with one another on the platform"}],
}

export const AdminExec = {
    header: "EXECUTIVE, MANAGEMENT & COMMITTEE (Exco, Management & Committee Activities Management)",
    checkedtext: ["This feature provides the required platform for all exco, management, committee members to relate without interference of non member.","The profile of each executive/committee member is attached to their basic information and their roles.","Past executives and their profiles can also be viewed by year or tenure. Toward a greater insight to the workings of this feature, please take note the following: -","Two employees cannot hold one position","An executive member can also be a committee member.","An executive position (portfolio) can either be removed or added by the admin only.","The admin uploads minute and reports for executive meetings.","Employees can belong to one or more committees.","Duties of each committee member can be added to committee profile."]
}

export const AdminResc = {
    header: "RESOURCES & PUBLICATIONS",
    checkedtext: ["The minutes of the various meetings can be added to resources page where they can be viewed, same is applicable to communique of meetings.","Minutes are placed in folders where all minutes of meetings can be viewed in line with given specifications, date, purpose etc.","Organizations with members that have research-based write-up and publications also have the opportunity to upload different publications.","All publications are forwarded to the admin or whoever is assigned by the admin for upload."]
}

export const AdminEmployee = {
    header: "EMPLOYEESHIP SEARCH",
    search: [{title:"Employees can search for other employees using criteria such as provided;",children: ["o Name,","o Department/Team,","o Year","o Other options as provided by admin."]}],
    checkedtext: ["Employees can search for; News, Insights, Events via time range, title and other options provided for at the set-up stage."]
}

export const AdminGallery = {
    header: "GALLERY",
    checkedtext: ["The gallery feature allows for the showcasing of various pictures from past events.","Preview videos from the community YouTube channel can also be viewed.","Videos can also be uploaded to the gallery section."]
}

export const AdminApp = {
    header: "APP SUBSCRIPTION MANAGEMENT",
    checkedtext: ["The application is a subscription based one and all employees are expected to be paid for by the subscribing organization a specified fee annually."],
    search: [{title:"Corporate Subscription:",children: ["o The organization purchasing the app pays in full for all employees so that all employees will not have to pay after joining."]}]
}

export const AdminAuth = {
    header: "AUTHENTICATION",
    subheader3: "INTEGRATION",
    checkedtext: ["This feature provides for security verification that bars non-employees from joining the community.","Approved users/employees will have to input specific details as created by the super admin to validate identity of intending user.","Users can only register if their data matches the data provided in the database submitted by the admin during setup.","There are two levels of database(s), the first database is for all employees and the second database is for employees who have registered/activated their accounts on the Rel8 app and have been confirmed."],
    search: [{title:"Rel8 Admin is designed to be integration friendly with existing people management or HIRS solutions.",children: [""]}],
}

export const AdminTicket = {
    header: "TICKETS & SUPPORT MANAGEMENT",
    checkedtext: ["This feature serves as a support service for employees who encounter issues.","Each issue is treated as a ticket and forwarded to admin who then pushes it to the Rel8 technical team for immediate attention.","Frequently asked questions as well as form to fill out details and complaints to be sent to admin."]
}