//STRUCTURE OF PRICING OBJECT
// const def = {
//     type: "",
//     features: []
// }

export const Membership = [
    {
    type: "Monthly",
    features: ["RESOURCES & PUBLICATIONS","MEMBERSHIP SEARCH","APP SUBSCRIPTION MANAGEMENT","NEWS TAB","GALLERY","TICKETS & SUPPORT MANAGEMENT","EVENT AND TRAINING MANAGEMENT TAB","CHAT MANAGEMENT","AUTHENTICATION","DUES & OTHER PAYMENT MANAGEMENT","EXECUTIVE & COMMITTEE (Exco Activities Management)"]
    },
    {
        type: "Yearly",
        features: ["RESOURCES & PUBLICATIONS","MEMBERSHIP SEARCH","APP SUBSCRIPTION MANAGEMENT","NEWS TAB","GALLERY","TICKETS & SUPPORT MANAGEMENT","EVENT AND TRAINING MANAGEMENT TAB","CHAT MANAGEMENT","AUTHENTICATION","DUES & OTHER PAYMENT MANAGEMENT","EXECUTIVE & COMMITTEE (Exco Activities Management)"]
    }
]

export const Administrator = [
    {
        type: "Monthly",
        features: ["RESOURCES & PUBLICATIONS","EMPLOYEE SEARCH","APP SUBSCRIPTION MANAGEMENT","NEWS TAB","GALLERY","SUPPORT MANAGEMENT","EVENT AND TRAINING MANAGEMENT TAB","CHAT MANAGEMENT","AUTHENTICATION","PAYMENT MANAGEMENT","EXECUTIVE & COMMITTEE (Exco Activities Management)"]
    },
    {
        type: "Yearly",
        features: ["RESOURCES & PUBLICATIONS","Employee SEARCH","APP SUBSCRIPTION MANAGEMENT","NEWS TAB","GALLERY","SUPPORT MANAGEMENT","EVENT AND TRAINING MANAGEMENT TAB","CHAT MANAGEMENT","AUTHENTICATION","PAYMENT MANAGEMENT","EXECUTIVE & COMMITTEE (Exco Activities Management)"]
    }
]